name: UC Test Case

on:
  push:
    branches: [ main, mayank/new/github-actions ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Running setup script
        run: ./scripts/examples/run-uc.sh
        
      # Runs a set of commands using the runners shell
      - name: Wait for connector to come online
        run: sleep 60

      - name: Checking for data transfer
        run: ./scripts/examples/checkData.sh
        
      - name: Stopping containers
        run: ./scripts/examples/stop-uc.sh
