name: Running example use case test

on:
  push:
    branches: [ main, mayank/new/github-actions ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Running setup script
        run: ./run.sh

      - name: Checking for data
        run: echo ${#$(curl http://localhost:8081)}
        
      # Runs a set of commands using the runners shell
      - name: Wait for connector to come online
        run: sleep 60
        
      - name: Checking for data
        run: echo ${#$(curl http://localhost:8081)}
        
      - name: Stopping containers
        run: ./stop.sh
